db:
  image: mysql:5.7
  restart: always
  volumes:
    - ./containers/db/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    - ./containers/db/init/:/docker-entrypoint-initdb.d/
  environment:
    MYSQL_ROOT_PASSWORD: pass

  container_name: db
app:
  build: .
  volumes:
    - .:/var/src/app
  ports:
    - '80:3000'
  environment:
    RAILS_ENV: development
    MYSQL_DATABASE: dev
  links:
    - db
    - node
  working_dir: /var/src/app
  command: /bin/sh -c "rm -f /var/src/app/tmp/pids/server.pid;bundle exec rails s -b 0.0.0.0"
  cap_add:
    - ALL  # Add all privilege
  container_name: app
  tty: true
  stdin_open: true
  privileged: true
  log_opt:
    max-size: "100k"
  dns:
    - 8.8.8.8
node:
  build: frontend
  working_dir: /var/src/app/frontend
  volumes:
    - ./frontend:/var/src/app/frontend:delegated
    - /var/src/app/frontend/node_modules
  ports:
    - 9090:8080
  command: ./node_modules/.bin/webpack-dev-server --host 0.0.0.0 --inline --progress --config build/webpack.dev.conf.js
  container_name: node
