db:
  image: mysql
  restart: always
  volumes:
    - ./containers/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./containers/db/initial.sql:/docker-entrypoint-initdb.d/initial.sql
  environment:
    MYSQL_ROOT_PASSWORD: pass
  container_name: db
app:
  build: .
  volumes:
    - .:/var/www/html
  ports:
    - '80:3000'
  environment:
    RAILS_ENV: development
    MYSQL_DATABASE: mydb
    DATABASE_USER: dev_user
    DATABASE_PASSWORD: secret
  links:
    - db
    - redis
  working_dir: /var/www/html
  command: bundle exec rails s -b '0.0.0.0'
  cap_add:
    - ALL  # Add all privilege
  container_name: app
  tty: true
  stdin_open: true
  privileged: true
  log_opt:
    max-size: "100k"
  dns:
    - 8.8.8.8
redis:
  image: redis
  restart: always
  container_name: redis
